---
name: "environment-variable-page-decoration"
github: "jenkinsci/environment-variable-page-decoration-plugin"
paths:
- "org/jenkins-ci/plugins/environment-variable-page-decoration"
developers:
- "tvon"
issues:
  type: jira
  value: "environment-variable-page-decoration-plugin"
