---
name: "build-configurator"
github: "jenkinsci/build-configurator-plugin"
paths: 
- "com/amcbridge/build-configurator"
developers: 
- "amcbridgedevteam"
issues:
  type: jira
  value: "build-configurator-plugin"
