---
name: "composer-security-checker"
github: "jenkinsci/composer-security-checker-plugin"
paths:
- "org/jenkins-ci/plugins/composer-security-checker"
developers:
- "easylo"
issues:
  type: jira
  value: "composer-security-checker-plugin"
