---
name: "config-autorefresh-plugin"
github: "jenkinsci/config-autorefresh-plugin"
paths:
- "org/jenkins-ci/plugins/config-autorefresh-plugin"
developers: []
issues:
  type: jira
  value: "config-autorefresh-plugin"
