---
name: "extended-security-settings"
github: "jenkinsci/extended-security-settings-plugin"
paths:
- "io/jenkins/plugins/extended-security-settings"
developers:
- "jvz"
- "jthompson"
- "wfollonier"
issues:
  type: jira
  value: "extended-security-settings-plugin"
