---
name: "azure-publishersettings-credentials"
github: "jenkinsci/azure-publishersettings-credentials-plugin"
paths:
- "org/jenkins-ci/plugins/azure-publishersettings-credentials"
developers:
- "batmat"
- "markwm"
issues:
  type: jira
  value: "azure-publishersettings-credentials-plugin"
