---
name: "environment-filter-utils"
github: "jenkinsci/environment-filter-utils-plugin"
paths:
  - "io/jenkins/plugins/environment-filter-utils"
developers:
  - "danielbeck"
issues:
  type: jira
  value: "environment-filter-utils-plugin"
