---
name: "lambdatest-automation"
github: "jenkinsci/lambdatest-automation-plugin"
paths:
- "org/jenkins-ci/plugins/lambdatest-automation"
developers:
- "lambdatest"
issues:
  type: jira
  value: "lambdatest-automation-plugin"
