---
name: "configurationslicing"
github: "jenkinsci/configurationslicing-plugin"
paths:
- "org/jenkins-ci/plugins/configurationslicing"
- "org/jvnet/hudson/plugins/configurationslicing"
developers:
- "mdonohue"
- "ninian"
- "guysoft"
issues:
  type: github
  value: "jenkinsci/configurationslicing-plugin"
