---
name: "probely-security"
github: "jenkinsci/probely-security-plugin"
paths:
- "io/jenkins/plugins/probely-security"
developers: 
- "poupas"
issues:
  type: jira
  value: "probely-security-plugin"
