---
name: "environment-script"
github: "jenkinsci/environment-script-plugin"
paths:
- "com/lookout/jenkins/environment-script"
developers:
- "dawidmalina"
issues:
  type: jira
  value: "environment-script-plugin"
