---
name: "spring-config"
github: "jenkinsci/spring-config-plugin"
paths:
- "io/jenkins/plugins/spring-config"
developers:
- "topikachu"
issues:
  type: github
  value: "jenkinsci/spring-config-plugin"
