---
name: "config-driven-pipeline"
github: "jenkinsci/config-driven-pipeline-plugin"
paths:
- "org/jenkins-ci/plugins/config-driven-pipeline"
developers:
- "justinharringa"
issues:
  type: github
  value: "jenkinsci/config-driven-pipeline-plugin"
