---
name: "build-environment"
github: "jenkinsci/build-environment-plugin"
paths:
- "org/jenkins-ci/plugins/build-environment"
developers:
- "stefanbrausch"
issues:
  type: jira
  value: "build-environment-plugin"
