---
name: "storable-configs-plugin"
github: "jenkinsci/storable-configs-plugin-plugin"
paths:
- "org/jvnet/hudson/plugins/storable-configs-plugin"
developers: []
issues:
  type: jira
  value: "storable-configs-plugin"
